apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-deployment-2
  labels:
    app: webapi
spec:
  replicas: 0
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapi
        image: handsonkubernetesonwinregistry.azurecr.io/webapife:1
        ports:
        - containerPort: 80
      imagePullSecrets: 
        - name: acr-pruebafe