apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-deployment-3
  labels:
    app: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapi
        image: handsonkubernetesonwinregistry.azurecr.io/webapife:1
        ports:
        - containerPort: 80
      imagePullSecrets: 
        - name: acr-pruebafe
---
apiVersion: v1
kind: Service
metadata:
  name: webapi-service-3
  labels:
    app: webapi
spec:
  type: ClusterIP
  selector:
    app: webapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
